static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: firewall_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: firewall_cluster
                  host_rewrite_literal: REPLACE       # Replace, because if it is a Knative service, it will be redirected to the original host (defined in the HOST header)
                  append_x_forwarded_host: true
          http_filters:
          # Lua filter to add the hostname
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local hostname = os.getenv("HOSTNAME")  -- Get the container's hostname
                  if hostname then
                    request_handle:headers():add("x-original-hostname", hostname)
                  end
                end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: firewall_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: firewall_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1      # REPLACE
                port_value: 80
