apiVersion: v1
kind: Namespace
metadata:
  name: mofaas
  labels:
    mofaas: nvp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: mofaas
data:
  envoy.yaml: |  # The Envoy configuration file
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: firewall_service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: firewall_cluster
              http_filters:
               # Lua filter to add the hostname
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  inline_code: |
                    function envoy_on_request(request_handle)
                      local hostname = os.getenv("HOSTNAME")  -- Get the container's hostname
                      if hostname then
                        request_handle:headers():add("x-original-hostname", hostname)
                      end
                    end
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      - name: firewall_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: firewall_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: proxy.proxy-test.svc.cluster.local
                    port_value: 8080
---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test
  namespace: mofaas
spec:
  template:
    metadata:
      labels:
        mofaas: nvp 
    spec:
      containers:
        - image: 10.43.67.161:5000/test
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test2
  namespace: mofaas
spec:
  template:
    metadata:
      labels:
        mofaas: nvp 
    spec:
      containers:
        - image: 10.43.67.161:5000/test
          env:
            - name: TARGET
              value: "Python Sample v1"
---
apiVersion: mofaas.atnog/v1
kind: MoFaaSFunction
metadata:
  name: my-function
  namespace: mofaas
spec:
  concurrency: 2
  variants:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    name: test
  - apiVersion: serving.knative.dev/v1
    kind: Service
    name: test2
  # - apiVersion: serving.knative.dev/v1
  #   kind: Service
  #   name: test
  ignore-headers:
  - ce-id
  - Date
  - x-envoy-upstream-service-time
