apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-containers
spec:
  background: false
  rules:
  - name: change-user-container-userid
    match:
      all:  # Logical OR: Match if either condition is true
      # Condition 1: Namespace has label "environment=dev"
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp  # Target namespaces with this label
      # Condition 2: Pod has label "inject-sidecar=true"
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas: nvp 
    mutate:
      foreach:
        - list: "request.object.spec.containers"
          patchesJson6902: |
            - path: "/spec/containers/{{elementIndex}}/securityContext"
              op: add
              value:
                runAsUser: 1000
                runAsGroup: 1000
          preconditions:
            key: "{{ element.name }}"
            operator: AnyNotIn
            value:
            - queue-proxy
  - name: inject-init-and-sidecar
    match:
      all:  # Logical OR: Match if either condition is true
      # Condition 1: Namespace has label "environment=dev"
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp  # Target namespaces with this label
      # Condition 2: Pod has label "inject-sidecar=true"
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas: nvp 
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
          - name: init-iptables
            image: 10.43.67.161:5000/init-iptables
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          # Add a sidecar container
          containers:
            - name: queue-proxy
              securityContext:
                runAsUser: 65532
                runAsGroup: 65532
            - name: envoy
              image: 10.43.67.161:5000/envoy:latest
              ports:
              - containerPort: 10000
              securityContext:
                runAsUser: 101
                runAsGroup: 101
              volumeMounts:
              - name: envoy-config
                mountPath: /etc/envoy
                readOnly: true
          volumes:
          - name: envoy-config
            configMap:
              name: envoy-config