apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-containers
spec:
  background: false
  rules:
  - name: inject-init-and-sidecar
    match:
      all:  # Logical OR: Match if either condition is true
      # Condition 1: Namespace has label "environment=dev"
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp  # Target namespaces with this label
      # Condition 2: Pod has label "inject-sidecar=true"
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas: nvp 
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
          - name: init-iptables
            image: alpine:3.14
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            command:
            - sh
            - -c
            - |
              apk update
              apk add iptables
              # apk add iptables && apk add tcpdump && apk add curl

              iptables -t nat -P PREROUTING ACCEPT
              iptables -t nat -P INPUT ACCEPT
              iptables -t nat -P OUTPUT ACCEPT
              iptables -t nat -P POSTROUTING ACCEPT
              iptables -t nat -N ISTIO_OUTPUT
              iptables -t nat -N ISTIO_REDIRECT
              iptables -t nat -A OUTPUT -p tcp -j ISTIO_OUTPUT
              # iptables -t nat -A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -j ISTIO_REDIRECT
              iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 101 -j RETURN
              iptables -t nat -A ISTIO_OUTPUT -m owner --gid-owner 101 -j RETURN
              iptables -t nat -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
              iptables -t nat -A ISTIO_OUTPUT -j ISTIO_REDIRECT
              iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 10000
          # Add a sidecar container
          containers:
            - name: envoy
              image: 10.43.67.161:5000/envoy:latest # envoyproxy/envoy:v1.33.0
              # args:
              # - "--config-path"
              # - "/etc/envoy/envoy.yaml"
              # - "--log-level"
              # - "trace"
              ports:
              - containerPort: 10000
              # - containerPort: 9901
              volumeMounts:
              - name: envoy-config
                mountPath: /etc/envoy
                readOnly: true
          volumes:
          - name: envoy-config
            configMap:
              name: envoy-config