apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-containers
spec:
  background: false
  rules:
  - name: change-user-container-userid
    match:
      all:  # Logical OR: Match if either condition is true
      # Condition 1: Namespace has label "environment=dev"
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp  # Target namespaces with this label
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-egress-proxy
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-chooser
    mutate:
      foreach:
        - list: "request.object.spec.containers"
          patchesJson6902: |
            - path: "/spec/containers/{{elementIndex}}/securityContext"
              op: add
              value:
                runAsUser: 1000
                runAsGroup: 1000
          preconditions:
            key: "{{ element.name }}"
            operator: AnyNotIn
            value:
            - queue-proxy
  - name: inject-init-and-sidecar
    match:
      all:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-egress-proxy
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-chooser
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
          - name: init-iptables
            image: ghcr.io/atnog/knative-mofaas/init-iptables:latest
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          # Add a sidecar container
          containers:
            - name: queue-proxy
              securityContext:
                runAsUser: 65532
                runAsGroup: 65532
            - name: envoy
              image: ghcr.io/atnog/knative-mofaas/envoy:latest
              ports:
              - containerPort: 10000
              securityContext:
                runAsUser: 101
                runAsGroup: 101
  - name: inject-envoy-configmap-volume-pod  # This could be integrated in the previous rule. However, it would be very difficult to exclude this specific rule from the MoFaaSFunc controller
    match:
      all:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchLabels:
              mofaas: nvp
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-egress-proxy
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              mofaas.atnog/service: mofaas-chooser
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - name: envoy
              volumeMounts:
              - name: envoy-config
                mountPath: /etc/envoy
                readOnly: true
          volumes:
          - name: envoy-config
            configMap:
              name: default-envoy-config
  - name: inject-envoy-configmap
    match:
      any:
      - resources:
          kinds:
            - Namespace
          selector:
            matchLabels:
              mofaas: nvp
    generate:
      kind: ConfigMap
      apiVersion: v1
      name: default-envoy-config
      namespace: "{{request.object.metadata.name}}"
      synchronize: true  # Ensures the ConfigMap stays in sync with the policy
      data:
        data:
          envoy.yaml: |  # The Envoy configuration file
            static_resources:
              listeners:
                - name: dynamic_forward_proxy_listener
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 10000
                  filter_chains:
                    - filters:
                        - name: envoy.filters.network.http_connection_manager
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                            stat_prefix: dynamic_forward_proxy
                            route_config:
                              name: local_route
                              virtual_hosts:
                                - name: dynamic_forward_proxy_service
                                  domains:
                                    - "*"
                                  routes:
                                    - match:
                                        prefix: "/"
                                      route:
                                        cluster: dynamic_forward_proxy_cluster
                            http_filters:
                              - name: envoy.filters.http.dynamic_forward_proxy
                                typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                                  dns_cache_config:
                                    name: dynamic_dns_cache
                                    dns_lookup_family: V4_ONLY
                              - name: envoy.filters.http.router
                                typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              clusters:
                - name: dynamic_forward_proxy_cluster
                  connect_timeout: 5s
                  lb_policy: CLUSTER_PROVIDED
                  cluster_type:
                    name: envoy.clusters.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
                      dns_cache_config:
                        name: dynamic_dns_cache
                        dns_lookup_family: V4_ONLY
