{{- $root := . -}}
{{- range .Values.multiVersionServices }}
{{- if eq .deploymentType "attack" }}
  {{- $svc := . }}
  {{- $serviceName := .name }}

apiVersion: mofaas.atnog/v1
kind: MoFaaSFunction
metadata:
  name: {{ $serviceName }}
  namespace: {{ $root.Values.namespace }}
spec:
  concurrency: {{ $svc.concurrency }}
  private: true
  variants:
  {{- range $svc.versions }}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    name: {{ $serviceName }}-{{ . }}
  {{- end }}
  ignore-headers:
  {{- range $svc.ignoreHeaders }}
  - {{ . }}
  {{- end }}
---
{{- end }}
{{- end }}
