apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  directus_api_token: {{ .Values.secrets.directusToken }}
  jwt_key: {{ .Values.secrets.jwtKey }}
  otp_secret: {{ .Values.secrets.otpSecret }}
