apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DIRECTUS_API_TOKEN: {{ .Values.secrets.directusToken }}
  JWT_KEY: {{ .Values.secrets.jwtKey }}
