{{- range .Values.oneVersionServices }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  template:
    metadata:
      {{- if .annotations }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - image: {{ $.Values.registry }}/{{ .name }}
          {{- if .env }}
          env:
            {{- range .env }}
              {{- $envName := . }}
              {{- range $.Values.commonEnv }}
                {{- if eq .name $envName }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretKeyRef.name }}
                  key: {{ .secretKeyRef.key }}
              {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
---
{{- end }}

{{- $root := . -}}
{{- range .Values.multiVersionServices }}
  {{- $svc := . }}
  {{- $serviceName := .name }}
  {{- range $root.Values.languages }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $serviceName }}-{{ . }}
  namespace: {{ $root.Values.namespace }}
spec:
  template:
    metadata:
      {{- if $svc.annotations }}
      annotations:
        {{- toYaml $svc.annotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - image: {{ $root.Values.registry }}/{{ $serviceName }}/{{ . }}
          {{- if $svc.env }}
          env:
            {{- range $svc.env }}
              {{- $envName := . }}
              {{- range $root.Values.commonEnv }}
                {{- if eq .name $envName }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretKeyRef.name }}
                  key: {{ .secretKeyRef.key }}
              {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
---
{{- end }}
{{- end }}
