apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-entry-point
  namespace: {{ .Values.namespace }}
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: entry-point
  sink:
    ref:
      apiVersion: mofaas.atnog/v1
      kind: MoFaaSFunction
      name: authorization
  # sink:
  #   ref:
  #     apiVersion: serving.knative.dev/v1
  #     kind: Service
  #     name: authorization-python
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-authorization
  namespace: {{ .Values.namespace }}
spec:
  # subject:
  #   apiVersion: serving.knative.dev/v1
  #   kind: Service
  #   name: authorization-python
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: mofaas-chooser-authorization
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-verify-transaction
  namespace: {{ .Values.namespace }}
spec:
  # subject:
  #   apiVersion: serving.knative.dev/v1
  #   kind: Service
  #   name: verify-transaction-python
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: mofaas-chooser-verify-transaction
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-transaction-result
  namespace: {{ .Values.namespace }}
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: transaction
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-egress-proxy-authorization-result
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: mofaas-egress-proxy-authorization
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-egress-proxy-verify-transaction-result
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: mofaas-egress-proxy-verify-transaction
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
