{{ $root := . -}}
{{ range .Values.multiVersionServices }}
{{ if eq .name "verify-transaction" }}
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: verify-transaction-trigger
  namespace: {{ $root.Values.namespace }}
spec:
  broker: broker
  filters:
    - exact:
        source: authorization
        dv: "true"
  subscriber:
    ref:
      {{ if eq .deploymentType "attack" }}
      apiVersion: mofaas.atnog/v1
      kind: MoFaaSFunction
      name: verify-transaction
      {{ else }}
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: verify-transaction-{{ .deploymentType }}
      {{ end }}
    uri: /
{{ end }}
{{ end }}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: authorization-bad-result-trigger
  namespace: {{ .Values.namespace }}
spec:
  broker: broker
  filters:
    - exact:
        source: authorization
    - not:
        exact:
          dv: "true"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
    uri: /
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transaction-trigger
  namespace: {{ .Values.namespace }}
spec:
  broker: broker
  filters:
    - exact:
        source: verify-transaction
        dt: "true"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: transaction
    uri: /
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: verify-transaction-bad-result-trigger
  namespace: {{ .Values.namespace }}
spec:
  broker: broker
  filters:
    - exact:
        source: verify-transaction
    - not:
        exact:
          dt: "true"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
    uri: /