apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: REPLACE
  namespace: REPLACE  # Replace with the appropriate namespace
spec:
  background: true
  exceptions:
    - policyName: inject-containers  # Replace with the name of your ClusterPolicy
      ruleNames:
        - inject-envoy-configmap-volume-pod  # Replace with the specific rule name to bypass
  match:
    any:
      - resources:
          kinds:
            - Pod
          selector:
            matchLabels: {}
              # REPLACE
