apiVersion: v1
kind: Namespace
metadata:
  name: mofaas-jwt-app
  labels:
    mofaas: nvp
---
apiVersion: v1
kind: Secret
metadata:
  name: directus-secret
  namespace: mofaas-jwt-app
type: Opaque
data:
  DIRECTUS_API_TOKEN: QmR0NXRZQ0RTTFMzLW42MmpVOFhndDFzWXJ6eWlwc1E=
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login-python
  namespace: mofaas-jwt-app
spec:
  template: 
    spec:
      containers:
        - image: 10.43.67.161:5000/jwt-app/login/python
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              value: very_secret_key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login-java
  namespace: mofaas-jwt-app
spec:
  template: 
    spec:
      containers:
        - image: 10.43.67.161:5000/jwt-app/login/java
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              value: very_secret_key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: get-secret-python
  namespace: mofaas-jwt-app
spec:
  template: 
    spec:
      containers:
        - image: 10.43.67.161:5000/jwt-app/get-secret/python
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              value: very_secret_key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: get-secret-java
  namespace: mofaas-jwt-app
spec:
  template: 
    spec:
      containers:
        - image: 10.43.67.161:5000/jwt-app/get-secret/java
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              value: very_secret_key
