---
# Source: mofaas-bank-app/templates/Secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secret
  namespace: mofaas-bank-app
type: Opaque
data:
  DIRECTUS_API_TOKEN: 
  JWT_KEY:
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login
  namespace: mofaas-bank-app
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/login
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entry-point
  namespace: mofaas-bank-app
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/entry-point
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transaction
  namespace: mofaas-bank-app
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/transaction
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result
  namespace: mofaas-bank-app
  annotations:
    autoscaling.knative.dev/max-scale: "1"
    autoscaling.knative.dev/min-scale: "1"
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/result
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization-python
  namespace: mofaas-bank-app
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/authorization/python
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Services.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: verify-transaction-python
  namespace: mofaas-bank-app
spec:
  template:
    spec:
      containers:
        - image: 10.43.67.161:5000/bank-app/verify-transaction/python
          env:
            - name: DIRECTUS_URL
              value: http://directus.directus:8055
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: DIRECTUS_API_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: JWT_KEY
---
# Source: mofaas-bank-app/templates/Broker.yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: broker
  namespace: mofaas-bank-app
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
---
# Source: mofaas-bank-app/templates/SinkBindings.yaml
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-entry-point
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: entry-point
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: authorization-python
---
# Source: mofaas-bank-app/templates/SinkBindings.yaml
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-authorization
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: authorization-python
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
---
# Source: mofaas-bank-app/templates/SinkBindings.yaml
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-verify-transaction
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: verify-transaction-python
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
---
# Source: mofaas-bank-app/templates/SinkBindings.yaml
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-transaction-result
  namespace: mofaas-bank-app
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: transaction
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
---
# Source: mofaas-bank-app/templates/Triggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: verify-transaction-trigger
  namespace: mofaas-bank-app
spec:
  broker: broker
  filters:
    - exact:
        source: authorization
        dv: "True"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: verify-transaction-python
    uri: /
---
# Source: mofaas-bank-app/templates/Triggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: authorization-bad-result-trigger
  namespace: mofaas-bank-app
spec:
  broker: broker
  filters:
    - exact:
        source: authorization
        dv: "False"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
    uri: /
---
# Source: mofaas-bank-app/templates/Triggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transaction-trigger
  namespace: mofaas-bank-app
spec:
  broker: broker
  filters:
    - exact:
        source: verify-transaction
        dt: "True"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: transaction
    uri: /
---
# Source: mofaas-bank-app/templates/Triggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: verify-transaction-bad-result-trigger
  namespace: mofaas-bank-app
spec:
  broker: broker
  filters:
    - exact:
        source: verify-transaction
        dt: "False"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
    uri: /
