namespace: mofaas-bank-app
registry: "10.43.67.161:5000/bank-app"
oneVersionServices:
  - name: login
    env:
      - DIRECTUS_URL
      - DIRECTUS_TOKEN
      - SECRET_KEY
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
  - name: entry-point
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
  - name: transaction
    env:
      - DIRECTUS_URL
      - DIRECTUS_TOKEN
    labels:
      networking.knative.dev/visibility: cluster-local
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
  - name: result
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
    labels:
      networking.knative.dev/visibility: cluster-local
multiVersionServices:
  - name: authorization
    deploymentType: java      # can be: attack, python, java, js, go, php
    env:
      - SECRET_KEY
    concurrency: 1
    versions:
      - python
      - java
      - php
      - js
      - go
    ignoreHeaders:
      - ce-id
      - Date
      - x-envoy-upstream-service-time
      - Content-Length
      - x-powered-by
    labels:
      networking.knative.dev/visibility: cluster-local
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
  - name: verify-transaction
    deploymentType: attack      # can be: attack, python, java, js, go, php
    env:
      - DIRECTUS_URL
      - DIRECTUS_TOKEN
      - OTP_SECRET
      - MAX_AMOUNT
    concurrency: 3
    versions:
      - python
      - java
      - php
      - js
      - go
    ignoreHeaders:
      - ce-id
      - Date
      - x-envoy-upstream-service-time
      - Content-Length
      - x-powered-by
    labels:
      networking.knative.dev/visibility: cluster-local
    annotations:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "1"
languages:
  - python
  - java
  - php
  - js
  - go
commonEnv:
  - name: DIRECTUS_TOKEN
    valueFrom:
      secretKeyRef:
        name: bank-app-secret
        key: directus_api_token
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: bank-app-secret
        key: jwt_key
  - name: OTP_SECRET
    valueFrom:
      secretKeyRef:
        name: bank-app-secret
        key: otp_secret
  - name: DIRECTUS_URL
    valueFrom:
      configMapKeyRef:
        name: bank-app-configmap
        key: directus_url
  - name: MAX_AMOUNT
    valueFrom:
      configMapKeyRef:
        name: bank-app-configmap
        key: max_amount
configmap:
  directusUrl: http://directus.directus:8055
  maxAmount: "15"
secrets:
  directusToken: QmR0NXRZQ0RTTFMzLW42MmpVOFhndDFzWXJ6eWlwc1E=
  jwtKey: dmVyeV9zZWNyZXRfa2V5
  otpSecret: MTIzNDU2
